const fs = require('fs');
const filePath = 'src/locales/i18n.ts';
let content = fs.readFileSync(filePath, 'utf8');

// Claves por idioma
const translations = {
  es: `      tourn_title: 'TORNEOS', tourn_sub: 'MUNDIAL 2026', tourn_support: 'SOPORTE: golziapp@gmail.com', tourn_create_btn: 'CREAR NUEVO TORNEO', tourn_join_btn: 'INSCRIBIRME', tourn_ranking_btn: 'VER RANKING', tourn_close_form: 'CERRAR FORMULARIO', tourn_create_action: 'CREAR TORNEO', tourn_creating: 'CREANDO TORNEO...', tourn_close: 'Cerrar', tourn_empty_title: 'SIN TORNEOS AÚN', tourn_empty_admin: 'Crea el primer torneo para tu liga.', tourn_empty_member: 'El administrador creará torneos aquí.', tourn_status_active: '🔴 ACTIVO', tourn_status_upcoming: '⏳ PRÓXIMO', tourn_status_finished: '🏅 FINALIZADO', tourn_public_badge: '🌍 PÚBLICO', tourn_label_start: 'INICIO', tourn_label_end: 'FIN', tourn_label_matches: 'PARTIDOS', tourn_label_members: 'INSCRITOS', tourn_joined: '✓ INSCRITO', tourn_form_name: 'NOMBRE DEL TORNEO *', tourn_form_desc: 'DESCRIPCIÓN (opcional)', tourn_form_prize1: '🥇 PREMIO 1ER LUGAR *', tourn_form_prize2: '🥈 PREMIO 2DO LUGAR (opcional)', tourn_form_prize3: '🥉 PREMIO 3ER LUGAR (opcional)', tourn_form_start: '📅 FECHA INICIO * (YYYY-MM-DD)', tourn_form_end: '📅 FECHA FIN * (YYYY-MM-DD)', tourn_form_city: '📌 CIUDAD *', tourn_form_country: '🌍 PAÍS *', tourn_form_web: '🌐 PÁGINA WEB (opcional)', tourn_form_max: '👥 LÍMITE DE INSCRITOS *', tourn_form_category: '🏢 CATEGORÍA DEL NEGOCIO', tourn_form_public: '🌍 TORNEO PÚBLICO', tourn_form_private: '🔒 TORNEO PRIVADO', tourn_form_public_hint: 'Visible para todos los usuarios de GOLZI', tourn_form_private_hint: 'Solo para miembros de tu liga', tourn_form_error: 'Completa los campos obligatorios marcados con *', tourn_no_preds: 'Sin predicciones aún', tourn_already_joined: 'Ya inscrito', tourn_already_joined_msg: 'Ya estás participando en este torneo', tourn_error_create: 'No se pudo crear el torneo', tourn_ph_name: 'Ej: Torneo Cuartos de Final', tourn_ph_desc: 'Describe el torneo...', tourn_ph_prize1: 'Ej: Cena para 2 + botella de vino', tourn_ph_prize2: 'Ej: Cupón 30% descuento', tourn_ph_prize3: 'Ej: Consumo gratis una noche', tourn_ph_city: 'Ej: Bogotá', tourn_ph_country: 'Ej: Colombia', tourn_ph_web: 'https://www.tunegocio.com', tourn_ph_max: 'Ej: 100',`,

  en: `      tourn_title: 'TOURNAMENTS', tourn_sub: 'WORLD CUP 2026', tourn_support: 'SUPPORT: golziapp@gmail.com', tourn_create_btn: 'CREATE NEW TOURNAMENT', tourn_join_btn: 'JOIN', tourn_ranking_btn: 'VIEW RANKING', tourn_close_form: 'CLOSE FORM', tourn_create_action: 'CREATE TOURNAMENT', tourn_creating: 'CREATING...', tourn_close: 'Close', tourn_empty_title: 'NO TOURNAMENTS YET', tourn_empty_admin: 'Create the first tournament for your league.', tourn_empty_member: 'The admin will create tournaments here.', tourn_status_active: '🔴 ACTIVE', tourn_status_upcoming: '⏳ UPCOMING', tourn_status_finished: '🏅 FINISHED', tourn_public_badge: '🌍 PUBLIC', tourn_label_start: 'START', tourn_label_end: 'END', tourn_label_matches: 'MATCHES', tourn_label_members: 'JOINED', tourn_joined: '✓ JOINED', tourn_form_name: 'TOURNAMENT NAME *', tourn_form_desc: 'DESCRIPTION (optional)', tourn_form_prize1: '🥇 1ST PLACE PRIZE *', tourn_form_prize2: '🥈 2ND PLACE PRIZE (optional)', tourn_form_prize3: '🥉 3RD PLACE PRIZE (optional)', tourn_form_start: '📅 START DATE * (YYYY-MM-DD)', tourn_form_end: '📅 END DATE * (YYYY-MM-DD)', tourn_form_city: '📌 CITY *', tourn_form_country: '🌍 COUNTRY *', tourn_form_web: '🌐 WEBSITE (optional)', tourn_form_max: '👥 MAX PARTICIPANTS *', tourn_form_category: '🏢 BUSINESS CATEGORY', tourn_form_public: '🌍 PUBLIC TOURNAMENT', tourn_form_private: '🔒 PRIVATE TOURNAMENT', tourn_form_public_hint: 'Visible to all GOLZI users', tourn_form_private_hint: 'Only for league members', tourn_form_error: 'Complete all required fields marked with *', tourn_no_preds: 'No predictions yet', tourn_already_joined: 'Already joined', tourn_already_joined_msg: 'You are already participating in this tournament', tourn_error_create: 'Could not create tournament', tourn_ph_name: 'Ex: Quarterfinals Tournament', tourn_ph_desc: 'Describe the tournament...', tourn_ph_prize1: 'Ex: Dinner for 2 + bottle of wine', tourn_ph_prize2: 'Ex: 30% discount coupon', tourn_ph_prize3: 'Ex: Free drinks for a night', tourn_ph_city: 'Ex: Miami', tourn_ph_country: 'Ex: USA', tourn_ph_web: 'https://www.yourbusiness.com', tourn_ph_max: 'Ex: 100',`,

  pt: `      tourn_title: 'TORNEIOS', tourn_sub: 'COPA DO MUNDO 2026', tourn_support: 'SUPORTE: golziapp@gmail.com', tourn_create_btn: 'CRIAR NOVO TORNEIO', tourn_join_btn: 'INSCREVER-ME', tourn_ranking_btn: 'VER RANKING', tourn_close_form: 'FECHAR FORMULÁRIO', tourn_create_action: 'CRIAR TORNEIO', tourn_creating: 'CRIANDO...', tourn_close: 'Fechar', tourn_empty_title: 'SEM TORNEIOS AINDA', tourn_empty_admin: 'Crie o primeiro torneio para sua liga.', tourn_empty_member: 'O administrador criará torneios aqui.', tourn_status_active: '🔴 ATIVO', tourn_status_upcoming: '⏳ PRÓXIMO', tourn_status_finished: '🏅 FINALIZADO', tourn_public_badge: '🌍 PÚBLICO', tourn_label_start: 'INÍCIO', tourn_label_end: 'FIM', tourn_label_matches: 'PARTIDAS', tourn_label_members: 'INSCRITOS', tourn_joined: '✓ INSCRITO', tourn_form_name: 'NOME DO TORNEIO *', tourn_form_desc: 'DESCRIÇÃO (opcional)', tourn_form_prize1: '🥇 PRÊMIO 1º LUGAR *', tourn_form_prize2: '🥈 PRÊMIO 2º LUGAR (opcional)', tourn_form_prize3: '🥉 PRÊMIO 3º LUGAR (opcional)', tourn_form_start: '📅 DATA INÍCIO * (YYYY-MM-DD)', tourn_form_end: '📅 DATA FIM * (YYYY-MM-DD)', tourn_form_city: '📌 CIDADE *', tourn_form_country: '🌍 PAÍS *', tourn_form_web: '🌐 SITE (opcional)', tourn_form_max: '👥 LIMITE DE INSCRITOS *', tourn_form_category: '🏢 CATEGORIA DO NEGÓCIO', tourn_form_public: '🌍 TORNEIO PÚBLICO', tourn_form_private: '🔒 TORNEIO PRIVADO', tourn_form_public_hint: 'Visível para todos os usuários GOLZI', tourn_form_private_hint: 'Apenas para membros da liga', tourn_form_error: 'Preencha todos os campos obrigatórios marcados com *', tourn_no_preds: 'Sem previsões ainda', tourn_already_joined: 'Já inscrito', tourn_already_joined_msg: 'Você já está participando deste torneio', tourn_error_create: 'Não foi possível criar o torneio', tourn_ph_name: 'Ex: Torneio Quartas de Final', tourn_ph_desc: 'Descreva o torneio...', tourn_ph_prize1: 'Ex: Jantar para 2 + garrafa de vinho', tourn_ph_prize2: 'Ex: Cupom 30% desconto', tourn_ph_prize3: 'Ex: Consumo grátis uma noite', tourn_ph_city: 'Ex: São Paulo', tourn_ph_country: 'Ex: Brasil', tourn_ph_web: 'https://www.seunegocio.com', tourn_ph_max: 'Ex: 100',`,

  fr: `      tourn_title: 'TOURNOIS', tourn_sub: 'COUPE DU MONDE 2026', tourn_support: 'SUPPORT: golziapp@gmail.com', tourn_create_btn: 'CRÉER UN TOURNOI', tourn_join_btn: "M'INSCRIRE", tourn_ranking_btn: 'VOIR CLASSEMENT', tourn_close_form: 'FERMER FORMULAIRE', tourn_create_action: 'CRÉER TOURNOI', tourn_creating: 'CRÉATION...', tourn_close: 'Fermer', tourn_empty_title: 'PAS ENCORE DE TOURNOIS', tourn_empty_admin: 'Créez le premier tournoi pour votre ligue.', tourn_empty_member: "L'admin créera des tournois ici.", tourn_status_active: '🔴 ACTIF', tourn_status_upcoming: '⏳ PROCHAIN', tourn_status_finished: '🏅 TERMINÉ', tourn_public_badge: '🌍 PUBLIC', tourn_label_start: 'DÉBUT', tourn_label_end: 'FIN', tourn_label_matches: 'MATCHS', tourn_label_members: 'INSCRITS', tourn_joined: '✓ INSCRIT', tourn_form_name: 'NOM DU TOURNOI *', tourn_form_desc: 'DESCRIPTION (optionnel)', tourn_form_prize1: '🥇 PRIX 1ÈRE PLACE *', tourn_form_prize2: '🥈 PRIX 2ÈME PLACE (optionnel)', tourn_form_prize3: '🥉 PRIX 3ÈME PLACE (optionnel)', tourn_form_start: '📅 DATE DÉBUT * (YYYY-MM-DD)', tourn_form_end: '📅 DATE FIN * (YYYY-MM-DD)', tourn_form_city: '📌 VILLE *', tourn_form_country: '🌍 PAYS *', tourn_form_web: '🌐 SITE WEB (optionnel)', tourn_form_max: '👥 MAX PARTICIPANTS *', tourn_form_category: '🏢 CATÉGORIE', tourn_form_public: '🌍 TOURNOI PUBLIC', tourn_form_private: '🔒 TOURNOI PRIVÉ', tourn_form_public_hint: 'Visible pour tous les utilisateurs GOLZI', tourn_form_private_hint: 'Réservé aux membres de la ligue', tourn_form_error: 'Complétez tous les champs obligatoires marqués avec *', tourn_no_preds: 'Pas encore de pronostics', tourn_already_joined: 'Déjà inscrit', tourn_already_joined_msg: 'Vous participez déjà à ce tournoi', tourn_error_create: 'Impossible de créer le tournoi', tourn_ph_name: 'Ex: Tournoi Quarts de Finale', tourn_ph_desc: 'Décrivez le tournoi...', tourn_ph_prize1: 'Ex: Dîner pour 2 + bouteille de vin', tourn_ph_prize2: 'Ex: Bon 30% réduction', tourn_ph_prize3: 'Ex: Consommations gratuites', tourn_ph_city: 'Ex: Paris', tourn_ph_country: 'Ex: France', tourn_ph_web: 'https://www.votrebusiness.com', tourn_ph_max: 'Ex: 100',`,

  de: `      tourn_title: 'TURNIERE', tourn_sub: 'WM 2026', tourn_support: 'SUPPORT: golziapp@gmail.com', tourn_create_btn: 'TURNIER ERSTELLEN', tourn_join_btn: 'ANMELDEN', tourn_ranking_btn: 'RANGLISTE', tourn_close_form: 'FORMULAR SCHLIESSEN', tourn_create_action: 'TURNIER ERSTELLEN', tourn_creating: 'ERSTELLE...', tourn_close: 'Schließen', tourn_empty_title: 'NOCH KEINE TURNIERE', tourn_empty_admin: 'Erstellen Sie das erste Turnier für Ihre Liga.', tourn_empty_member: 'Der Admin wird hier Turniere erstellen.', tourn_status_active: '🔴 AKTIV', tourn_status_upcoming: '⏳ BEVORSTEHEND', tourn_status_finished: '🏅 BEENDET', tourn_public_badge: '🌍 ÖFFENTLICH', tourn_label_start: 'START', tourn_label_end: 'ENDE', tourn_label_matches: 'SPIELE', tourn_label_members: 'TEILNEHMER', tourn_joined: '✓ ANGEMELDET', tourn_form_name: 'TURNIERNAME *', tourn_form_desc: 'BESCHREIBUNG (optional)', tourn_form_prize1: '🥇 1. PLATZ PREIS *', tourn_form_prize2: '🥈 2. PLATZ PREIS (optional)', tourn_form_prize3: '🥉 3. PLATZ PREIS (optional)', tourn_form_start: '📅 STARTDATUM * (YYYY-MM-DD)', tourn_form_end: '📅 ENDDATUM * (YYYY-MM-DD)', tourn_form_city: '📌 STADT *', tourn_form_country: '🌍 LAND *', tourn_form_web: '🌐 WEBSEITE (optional)', tourn_form_max: '👥 MAX TEILNEHMER *', tourn_form_category: '🏢 KATEGORIE', tourn_form_public: '🌍 ÖFFENTLICHES TURNIER', tourn_form_private: '🔒 PRIVATES TURNIER', tourn_form_public_hint: 'Für alle GOLZI-Nutzer sichtbar', tourn_form_private_hint: 'Nur für Liga-Mitglieder', tourn_form_error: 'Bitte alle Pflichtfelder ausfüllen *', tourn_no_preds: 'Noch keine Vorhersagen', tourn_already_joined: 'Bereits angemeldet', tourn_already_joined_msg: 'Sie nehmen bereits an diesem Turnier teil', tourn_error_create: 'Turnier konnte nicht erstellt werden', tourn_ph_name: 'Bsp: Viertelfinale Turnier', tourn_ph_desc: 'Beschreiben Sie das Turnier...', tourn_ph_prize1: 'Bsp: Abendessen für 2', tourn_ph_prize2: 'Bsp: 30% Rabatt', tourn_ph_prize3: 'Bsp: Freigetränke', tourn_ph_city: 'Bsp: Berlin', tourn_ph_country: 'Bsp: Deutschland', tourn_ph_web: 'https://www.ihrgeschaeft.de', tourn_ph_max: 'Bsp: 100',`,

  it: `      tourn_title: 'TORNEI', tourn_sub: 'MONDIALE 2026', tourn_support: 'SUPPORTO: golziapp@gmail.com', tourn_create_btn: 'CREA NUOVO TORNEO', tourn_join_btn: 'ISCRIVIMI', tourn_ranking_btn: 'VEDI CLASSIFICA', tourn_close_form: 'CHIUDI MODULO', tourn_create_action: 'CREA TORNEO', tourn_creating: 'CREANDO...', tourn_close: 'Chiudi', tourn_empty_title: 'NESSUN TORNEO ANCORA', tourn_empty_admin: 'Crea il primo torneo per la tua lega.', tourn_empty_member: "L'admin creerà tornei qui.", tourn_status_active: '🔴 ATTIVO', tourn_status_upcoming: '⏳ PROSSIMO', tourn_status_finished: '🏅 TERMINATO', tourn_public_badge: '🌍 PUBBLICO', tourn_label_start: 'INIZIO', tourn_label_end: 'FINE', tourn_label_matches: 'PARTITE', tourn_label_members: 'ISCRITTI', tourn_joined: '✓ ISCRITTO', tourn_form_name: 'NOME DEL TORNEO *', tourn_form_desc: 'DESCRIZIONE (opzionale)', tourn_form_prize1: '🥇 PREMIO 1° POSTO *', tourn_form_prize2: '🥈 PREMIO 2° POSTO (opzionale)', tourn_form_prize3: '🥉 PREMIO 3° POSTO (opzionale)', tourn_form_start: '📅 DATA INIZIO * (YYYY-MM-DD)', tourn_form_end: '📅 DATA FINE * (YYYY-MM-DD)', tourn_form_city: '📌 CITTÀ *', tourn_form_country: '🌍 PAESE *', tourn_form_web: '🌐 SITO WEB (opzionale)', tourn_form_max: '👥 MAX PARTECIPANTI *', tourn_form_category: '🏢 CATEGORIA', tourn_form_public: '🌍 TORNEO PUBBLICO', tourn_form_private: '🔒 TORNEO PRIVATO', tourn_form_public_hint: 'Visibile a tutti gli utenti GOLZI', tourn_form_private_hint: 'Solo per i membri della lega', tourn_form_error: 'Completa tutti i campi obbligatori contrassegnati con *', tourn_no_preds: 'Nessun pronostico ancora', tourn_already_joined: 'Già iscritto', tourn_already_joined_msg: 'Stai già partecipando a questo torneo', tourn_error_create: 'Impossibile creare il torneo', tourn_ph_name: 'Es: Torneo Quarti di Finale', tourn_ph_desc: 'Descrivi il torneo...', tourn_ph_prize1: 'Es: Cena per 2 + bottiglia di vino', tourn_ph_prize2: 'Es: Buono sconto 30%', tourn_ph_prize3: 'Es: Consumazioni gratis', tourn_ph_city: 'Es: Roma', tourn_ph_country: 'Es: Italia', tourn_ph_web: 'https://www.tuolocale.it', tourn_ph_max: 'Es: 100',`,

  ru: `      tourn_title: 'ТУРНИРЫ', tourn_sub: 'ЧМ 2026', tourn_support: 'ПОДДЕРЖКА: golziapp@gmail.com', tourn_create_btn: 'СОЗДАТЬ ТУРНИР', tourn_join_btn: 'ЗАПИСАТЬСЯ', tourn_ranking_btn: 'РЕЙТИНГ', tourn_close_form: 'ЗАКРЫТЬ', tourn_create_action: 'СОЗДАТЬ', tourn_creating: 'СОЗДАНИЕ...', tourn_close: 'Закрыть', tourn_empty_title: 'НЕТ ТУРНИРОВ', tourn_empty_admin: 'Создайте первый турнир для вашей лиги.', tourn_empty_member: 'Администратор создаст турниры здесь.', tourn_status_active: '🔴 АКТИВНЫЙ', tourn_status_upcoming: '⏳ СКОРО', tourn_status_finished: '🏅 ЗАВЕРШЁН', tourn_public_badge: '🌍 ПУБЛИЧНЫЙ', tourn_label_start: 'НАЧАЛО', tourn_label_end: 'КОНЕЦ', tourn_label_matches: 'МАТЧИ', tourn_label_members: 'УЧАСТНИКИ', tourn_joined: '✓ ЗАПИСАН', tourn_form_name: 'НАЗВАНИЕ ТУРНИРА *', tourn_form_desc: 'ОПИСАНИЕ (необязательно)', tourn_form_prize1: '🥇 ПРИЗ 1 МЕСТО *', tourn_form_prize2: '🥈 ПРИЗ 2 МЕСТО (необязательно)', tourn_form_prize3: '🥉 ПРИЗ 3 МЕСТО (необязательно)', tourn_form_start: '📅 ДАТА НАЧАЛА * (YYYY-MM-DD)', tourn_form_end: '📅 ДАТА КОНЦА * (YYYY-MM-DD)', tourn_form_city: '📌 ГОРОД *', tourn_form_country: '🌍 СТРАНА *', tourn_form_web: '🌐 САЙТ (необязательно)', tourn_form_max: '👥 МАКС УЧАСТНИКОВ *', tourn_form_category: '🏢 КАТЕГОРИЯ', tourn_form_public: '🌍 ПУБЛИЧНЫЙ ТУРНИР', tourn_form_private: '🔒 ЧАСТНЫЙ ТУРНИР', tourn_form_public_hint: 'Видно всем пользователям GOLZI', tourn_form_private_hint: 'Только для членов лиги', tourn_form_error: 'Заполните все обязательные поля *', tourn_no_preds: 'Нет прогнозов', tourn_already_joined: 'Уже записан', tourn_already_joined_msg: 'Вы уже участвуете в этом турнире', tourn_error_create: 'Не удалось создать турнир', tourn_ph_name: 'Пр: Турнир четвертьфинала', tourn_ph_desc: 'Опишите турнир...', tourn_ph_prize1: 'Пр: Ужин на 2', tourn_ph_prize2: 'Пр: Скидка 30%', tourn_ph_prize3: 'Пр: Бесплатные напитки', tourn_ph_city: 'Пр: Москва', tourn_ph_country: 'Пр: Россия', tourn_ph_web: 'https://www.vashbiznes.ru', tourn_ph_max: 'Пр: 100',`,

  ar: `      tourn_title: 'البطولات', tourn_sub: 'كأس العالم 2026', tourn_support: 'الدعم: golziapp@gmail.com', tourn_create_btn: 'إنشاء بطولة', tourn_join_btn: 'الانضمام', tourn_ranking_btn: 'الترتيب', tourn_close_form: 'إغلاق', tourn_create_action: 'إنشاء', tourn_creating: 'جارٍ الإنشاء...', tourn_close: 'إغلاق', tourn_empty_title: 'لا بطولات بعد', tourn_empty_admin: 'أنشئ أول بطولة لدوريك.', tourn_empty_member: 'سيقوم المسؤول بإنشاء البطولات هنا.', tourn_status_active: '🔴 نشط', tourn_status_upcoming: '⏳ قادم', tourn_status_finished: '🏅 منتهي', tourn_public_badge: '🌍 عام', tourn_label_start: 'البداية', tourn_label_end: 'النهاية', tourn_label_matches: 'المباريات', tourn_label_members: 'المشاركون', tourn_joined: '✓ مسجل', tourn_form_name: 'اسم البطولة *', tourn_form_desc: 'الوصف (اختياري)', tourn_form_prize1: '🥇 جائزة المركز الأول *', tourn_form_prize2: '🥈 جائزة المركز الثاني (اختياري)', tourn_form_prize3: '🥉 جائزة المركز الثالث (اختياري)', tourn_form_start: '📅 تاريخ البداية * (YYYY-MM-DD)', tourn_form_end: '📅 تاريخ النهاية * (YYYY-MM-DD)', tourn_form_city: '📌 المدينة *', tourn_form_country: '🌍 البلد *', tourn_form_web: '🌐 الموقع (اختياري)', tourn_form_max: '👥 الحد الأقصى للمشاركين *', tourn_form_category: '🏢 الفئة', tourn_form_public: '🌍 بطولة عامة', tourn_form_private: '🔒 بطولة خاصة', tourn_form_public_hint: 'مرئي لجميع مستخدمي GOLZI', tourn_form_private_hint: 'للأعضاء فقط', tourn_form_error: 'أكمل جميع الحقول الإلزامية *', tourn_no_preds: 'لا تنبؤات بعد', tourn_already_joined: 'مسجل بالفعل', tourn_already_joined_msg: 'أنت مشارك بالفعل في هذه البطولة', tourn_error_create: 'تعذر إنشاء البطولة', tourn_ph_name: 'مثال: بطولة ربع النهائي', tourn_ph_desc: 'صف البطولة...', tourn_ph_prize1: 'مثال: عشاء لاثنين', tourn_ph_prize2: 'مثال: خصم 30%', tourn_ph_prize3: 'مثال: مشروبات مجانية', tourn_ph_city: 'مثال: دبي', tourn_ph_country: 'مثال: الإمارات', tourn_ph_web: 'https://www.yourbusiness.com', tourn_ph_max: 'مثال: 100',`,

  zh: `      tourn_title: '锦标赛', tourn_sub: '世界杯2026', tourn_support: '支持: golziapp@gmail.com', tourn_create_btn: '创建锦标赛', tourn_join_btn: '报名', tourn_ranking_btn: '排名', tourn_close_form: '关闭', tourn_create_action: '创建', tourn_creating: '创建中...', tourn_close: '关闭', tourn_empty_title: '暂无锦标赛', tourn_empty_admin: '为您的联赛创建第一个锦标赛。', tourn_empty_member: '管理员将在此创建锦标赛。', tourn_status_active: '🔴 进行中', tourn_status_upcoming: '⏳ 即将开始', tourn_status_finished: '🏅 已结束', tourn_public_badge: '🌍 公开', tourn_label_start: '开始', tourn_label_end: '结束', tourn_label_matches: '比赛', tourn_label_members: '参赛者', tourn_joined: '✓ 已报名', tourn_form_name: '锦标赛名称 *', tourn_form_desc: '描述（可选）', tourn_form_prize1: '🥇 第一名奖品 *', tourn_form_prize2: '🥈 第二名奖品（可选）', tourn_form_prize3: '🥉 第三名奖品（可选）', tourn_form_start: '📅 开始日期 * (YYYY-MM-DD)', tourn_form_end: '📅 结束日期 * (YYYY-MM-DD)', tourn_form_city: '📌 城市 *', tourn_form_country: '🌍 国家 *', tourn_form_web: '🌐 网站（可选）', tourn_form_max: '👥 最大参赛人数 *', tourn_form_category: '🏢 商业类别', tourn_form_public: '🌍 公开锦标赛', tourn_form_private: '🔒 私人锦标赛', tourn_form_public_hint: '对所有GOLZI用户可见', tourn_form_private_hint: '仅限联赛成员', tourn_form_error: '请填写所有标有*的必填字段', tourn_no_preds: '暂无预测', tourn_already_joined: '已报名', tourn_already_joined_msg: '您已参加此锦标赛', tourn_error_create: '无法创建锦标赛', tourn_ph_name: '例：四分之一决赛锦标赛', tourn_ph_desc: '描述锦标赛...', tourn_ph_prize1: '例：两人晚餐', tourn_ph_prize2: '例：九折优惠券', tourn_ph_prize3: '例：免费饮品一晚', tourn_ph_city: '例：上海', tourn_ph_country: '例：中国', tourn_ph_web: 'https://www.yourbusiness.com', tourn_ph_max: '例：100',`,

  ja: `      tourn_title: 'トーナメント', tourn_sub: 'ワールドカップ2026', tourn_support: 'サポート: golziapp@gmail.com', tourn_create_btn: 'トーナメント作成', tourn_join_btn: '参加する', tourn_ranking_btn: 'ランキング', tourn_close_form: '閉じる', tourn_create_action: '作成する', tourn_creating: '作成中...', tourn_close: '閉じる', tourn_empty_title: 'トーナメントなし', tourn_empty_admin: 'リーグの最初のトーナメントを作成してください。', tourn_empty_member: '管理者がここにトーナメントを作成します。', tourn_status_active: '🔴 開催中', tourn_status_upcoming: '⏳ 予定', tourn_status_finished: '🏅 終了', tourn_public_badge: '🌍 公開', tourn_label_start: '開始', tourn_label_end: '終了', tourn_label_matches: '試合', tourn_label_members: '参加者', tourn_joined: '✓ 参加済み', tourn_form_name: 'トーナメント名 *', tourn_form_desc: '説明（任意）', tourn_form_prize1: '🥇 1位賞品 *', tourn_form_prize2: '🥈 2位賞品（任意）', tourn_form_prize3: '🥉 3位賞品（任意）', tourn_form_start: '📅 開始日 * (YYYY-MM-DD)', tourn_form_end: '📅 終了日 * (YYYY-MM-DD)', tourn_form_city: '📌 都市 *', tourn_form_country: '🌍 国 *', tourn_form_web: '🌐 ウェブサイト（任意）', tourn_form_max: '👥 最大参加者数 *', tourn_form_category: '🏢 ビジネスカテゴリ', tourn_form_public: '🌍 公開トーナメント', tourn_form_private: '🔒 プライベートトーナメント', tourn_form_public_hint: 'すべてのGOLZIユーザーに表示', tourn_form_private_hint: 'リーグメンバーのみ', tourn_form_error: '*の必須項目をすべて入力してください', tourn_no_preds: 'まだ予測なし', tourn_already_joined: '参加済み', tourn_already_joined_msg: 'すでにこのトーナメントに参加しています', tourn_error_create: 'トーナメントを作成できませんでした', tourn_ph_name: '例：準々決勝トーナメント', tourn_ph_desc: 'トーナメントを説明...', tourn_ph_prize1: '例：2名様ディナー', tourn_ph_prize2: '例：30%割引クーポン', tourn_ph_prize3: '例：無料ドリンク', tourn_ph_city: '例：東京', tourn_ph_country: '例：日本', tourn_ph_web: 'https://www.yourbusiness.jp', tourn_ph_max: '例：100',`,

  ko: `      tourn_title: '토너먼트', tourn_sub: '월드컵 2026', tourn_support: '지원: golziapp@gmail.com', tourn_create_btn: '토너먼트 만들기', tourn_join_btn: '참가하기', tourn_ranking_btn: '순위 보기', tourn_close_form: '닫기', tourn_create_action: '만들기', tourn_creating: '생성 중...', tourn_close: '닫기', tourn_empty_title: '토너먼트 없음', tourn_empty_admin: '리그의 첫 번째 토너먼트를 만드세요.', tourn_empty_member: '관리자가 여기에 토너먼트를 만들 것입니다.', tourn_status_active: '🔴 진행 중', tourn_status_upcoming: '⏳ 예정', tourn_status_finished: '🏅 종료', tourn_public_badge: '🌍 공개', tourn_label_start: '시작', tourn_label_end: '종료', tourn_label_matches: '경기', tourn_label_members: '참가자', tourn_joined: '✓ 참가됨', tourn_form_name: '토너먼트 이름 *', tourn_form_desc: '설명 (선택)', tourn_form_prize1: '🥇 1위 상품 *', tourn_form_prize2: '🥈 2위 상품 (선택)', tourn_form_prize3: '🥉 3위 상품 (선택)', tourn_form_start: '📅 시작일 * (YYYY-MM-DD)', tourn_form_end: '📅 종료일 * (YYYY-MM-DD)', tourn_form_city: '📌 도시 *', tourn_form_country: '🌍 국가 *', tourn_form_web: '🌐 웹사이트 (선택)', tourn_form_max: '👥 최대 참가자 수 *', tourn_form_category: '🏢 비즈니스 카테고리', tourn_form_public: '🌍 공개 토너먼트', tourn_form_private: '🔒 비공개 토너먼트', tourn_form_public_hint: '모든 GOLZI 사용자에게 표시', tourn_form_private_hint: '리그 멤버만', tourn_form_error: '*로 표시된 필수 항목을 모두 입력하세요', tourn_no_preds: '아직 예측 없음', tourn_already_joined: '이미 참가함', tourn_already_joined_msg: '이미 이 토너먼트에 참가하고 있습니다', tourn_error_create: '토너먼트를 만들 수 없습니다', tourn_ph_name: '예: 8강 토너먼트', tourn_ph_desc: '토너먼트 설명...', tourn_ph_prize1: '예: 2인 저녁 식사', tourn_ph_prize2: '예: 30% 할인 쿠폰', tourn_ph_prize3: '예: 무료 음료', tourn_ph_city: '예: 서울', tourn_ph_country: '예: 한국', tourn_ph_web: 'https://www.yourbusiness.kr', tourn_ph_max: '예: 100',`,

  hi: `      tourn_title: 'टूर्नामेंट', tourn_sub: 'विश्व कप 2026', tourn_support: 'सहायता: golziapp@gmail.com', tourn_create_btn: 'नया टूर्नामेंट बनाएं', tourn_join_btn: 'शामिल हों', tourn_ranking_btn: 'रैंकिंग देखें', tourn_close_form: 'बंद करें', tourn_create_action: 'बनाएं', tourn_creating: 'बना रहे हैं...', tourn_close: 'बंद करें', tourn_empty_title: 'अभी कोई टूर्नामेंट नहीं', tourn_empty_admin: 'अपनी लीग के लिए पहला टूर्नामेंट बनाएं।', tourn_empty_member: 'एडमिन यहाँ टूर्नामेंट बनाएगा।', tourn_status_active: '🔴 सक्रिय', tourn_status_upcoming: '⏳ आगामी', tourn_status_finished: '🏅 समाप्त', tourn_public_badge: '🌍 सार्वजनिक', tourn_label_start: 'शुरू', tourn_label_end: 'अंत', tourn_label_matches: 'मैच', tourn_label_members: 'प्रतिभागी', tourn_joined: '✓ शामिल', tourn_form_name: 'टूर्नामेंट का नाम *', tourn_form_desc: 'विवरण (वैकल्पिक)', tourn_form_prize1: '🥇 प्रथम स्थान पुरस्कार *', tourn_form_prize2: '🥈 द्वितीय स्थान पुरस्कार (वैकल्पिक)', tourn_form_prize3: '🥉 तृतीय स्थान पुरस्कार (वैकल्पिक)', tourn_form_start: '📅 शुरू तारीख * (YYYY-MM-DD)', tourn_form_end: '📅 अंत तारीख * (YYYY-MM-DD)', tourn_form_city: '📌 शहर *', tourn_form_country: '🌍 देश *', tourn_form_web: '🌐 वेबसाइट (वैकल्पिक)', tourn_form_max: '👥 अधिकतम प्रतिभागी *', tourn_form_category: '🏢 व्यवसाय श्रेणी', tourn_form_public: '🌍 सार्वजनिक टूर्नामेंट', tourn_form_private: '🔒 निजी टूर्नामेंट', tourn_form_public_hint: 'सभी GOLZI उपयोगकर्ताओं को दिखाई देता है', tourn_form_private_hint: 'केवल लीग सदस्यों के लिए', tourn_form_error: '* से चिह्नित सभी आवश्यक फ़ील्ड भरें', tourn_no_preds: 'अभी कोई भविष्यवाणी नहीं', tourn_already_joined: 'पहले से शामिल', tourn_already_joined_msg: 'आप पहले से इस टूर्नामेंट में भाग ले रहे हैं', tourn_error_create: 'टूर्नामेंट नहीं बना सका', tourn_ph_name: 'उदा: क्वार्टर फाइनल टूर्नामेंट', tourn_ph_desc: 'टूर्नामेंट का वर्णन करें...', tourn_ph_prize1: 'उदा: 2 के लिए रात का खाना', tourn_ph_prize2: 'उदा: 30% छूट कूपन', tourn_ph_prize3: 'उदा: मुफ्त पेय एक रात', tourn_ph_city: 'उदा: मुंबई', tourn_ph_country: 'उदा: भारत', tourn_ph_web: 'https://www.yourbusiness.in', tourn_ph_max: 'उदा: 100',`,
};

// Anclas para cada idioma — insertar antes del cierre de cada bloque translation
const anchors = {
  es: `      mundial_equipo: 'EQUIPO',`,
  en: `      ranking_share: 'SHARE',`,
  pt: `      ranking_share: 'COMPARTILHAR',`,
  fr: `      ranking_share: 'PARTAGER',`,
  de: `      ranking_share: 'TEILEN',`,
  it: `      ranking_share: 'CONDIVIDI',`,
  ru: `      ranking_share: 'ПОДЕЛИТЬСЯ',`,
  ar: `      ranking_share: 'مشاركة',`,
  zh: `      ranking_share: 'Õêåõ║½',`,
  ja: `      ranking_share: 'ÒéÀÒéºÒéó',`,
  ko: `      ranking_share: 'Û│Áý£á',`,
  hi: `      ranking_share: 'शेयर करें',`,
};

let count = 0;
for (const [lang, anchor] of Object.entries(anchors)) {
  const translation = translations[lang];
  if (!translation) { console.log(`⚠️  Sin traducción para ${lang}`); continue; }
  if (content.includes(`tourn_title:`)) {
    // Ya existe, saltar
    if (content.indexOf(`tourn_title:`) < content.indexOf(anchor) + 1000) {
      console.log(`⚠️  ${lang}: claves ya existen, saltando`);
      continue;
    }
  }
  if (content.includes(anchor)) {
    content = content.replace(anchor, `${translation}\n${anchor}`);
    count++;
    console.log(`✅ ${lang}: claves agregadas`);
  } else {
    console.log(`⚠️  ${lang}: ancla no encontrada — "${anchor.substring(0, 50)}"`);
  }
}

fs.writeFileSync(filePath, content, 'utf8');
console.log(`\n✅ ${count} idiomas actualizados en i18n.ts`);
